version: '3.8'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - mongo

  hrrs-mongo:
    image: mongo:latest
    container_name: hrrs-mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    name: mongo-db
